# Generated by Django 3.1.5 on 2021-02-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogappserver', '0003_auto_20210211_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
